pipeline {
    agent any



    stages {
        stage('build-mpy-cross') {
                steps {
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                    sh "cd mpy-cross & make "
                }
            }

    }
}
